### ISSUE TITLE
invalid multibyte escape: /[\r\n\x80-\xff]/

### ISSUE THREAD

**Issue by danielpclark** [martinpovolny/vformat-ruby#1]
Both Ruby 1.9.3 and Ruby 2.1.2 raise this error.

```
require 'vformat'
SyntaxError: /home/user/dev/vformat-ruby/lib/vformat/encoder.rb:478: invalid multibyte escape: /[\r\n\x80-\xff]/
    from /home/user/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /home/user/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /home/user/dev/vformat-ruby/lib/vformat.rb:356:in `<top (required)>'
    from /home/user/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /home/user/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from (irb):2
    from /home/user/.rvm/rubies/ruby-2.1.2/bin/irb:11:in `<main>'
```

I'm not having any luck using `# encoding: US-ASCII` either.

**Comment by forgottentea-xx** [comment]
rugged

**Comment by marek-veber** [comment]
this issue is just fixed in the code, try checkout latest version
